### PR TITLE
How long to wait

### PR DESCRIPTION
**Pull request by znicholls**
@andrewgsavage I don't actually want to pull, I just can't work out how to make an issue in my fork/otherwise contact you haha

Anyway, given the lack of response in pint (I know it's been a day, but given the interest I thought this might have stirred the waters a bit more), do you want to set a timeline on how long we wait before we just do something like `cyberpandas` and simply put all wrapping stuff in a separate repo which simply wraps `pint`? My only concern with this is that we then couldn't make changes to e.g. `quantity` which I'm guessing would be an issue?

### CODE REVIEW

**Comment by andrewgsavage** [comment]
I'm not sure that's possible as the @check_implemented decorator is necessary - Without it, PA + Q_ works, but Q_ + PA throws a DimensionalityError. 

That was the cleanest way I could find to get Q_ + PA to return NotImplemented. Do you know of any ways to change that behavior as a separate library?

**Comment by znicholls** [comment]
> I'm not sure that's possible as the @check_implemented decorator is necessary

Hmm bugger, hopefully we get an answer sooner rather than later then, we can always work from this fork in the meantime...

> Do you know of any ways to change that behavior as a separate library?

Nope I have I haven't had a chance to understand what you did yet unfortunately

**Comment by znicholls** [comment]
@andrewgsavage if you want to merge this in, would it be possible to rebase first?

**Comment by andrewgsavage** [comment]
Yea if you can give me a hand with it!

**Pull request closed without merging**
