### PR TITLE
Rebase result

### PR DESCRIPTION
**Pull request by znicholls**

### CODE REVIEW

**Comment by znicholls** [comment]
@andrewgsavage this shows the result I think we can expect. Do the diffs look as expected to you?

**Comment by andrewgsavage** [comment]
Yea that's what I was expecting

e: Actually there should be some series accessor tests

**Comment by znicholls** [comment]
Sweet merge at will then

**Comment by andrewgsavage** [comment]
Eek guess you missed this edit:
> e: Actually there should be some series accessor tests

**Comment by znicholls** [comment]
> Eek guess you missed this edit:

Hmm that can happen, hence why always best to check. Anyway all good!

**Comment by znicholls** [comment]
Did the tests get added in the end? The network graph looks wrong... https://github.com/znicholls/pint/network

**Comment by znicholls** [comment]
sorry ignore my comments here, only just saw #9

**Pull request merged**
