### PR TITLE
WIP: fix pandas tests

### PR DESCRIPTION
**Pull request by znicholls**
Cheat way to run CI

### CODE REVIEW

**Comment by znicholls** [comment]
@andrewgsavage looks wicked!

Are you happy with the following:

- merge this in
- I'll have a look tomorrow and make any suggested changes in new merge requests
- once we're both happy, we reignite conversations in the main pint and pandas repos?
    - on this note, are there any gotchas that still aren't behaving?

**Comment by andrewgsavage** [comment]
That sounds good.

I couldn't get the test_arith_series_with_array pandas test working - pandas performs (s op arr) and s.combine(arr,op). I think this should be tested without the _check_op funcs.

When trying to get the test_initialisation working 
pd.Series([q for q in strt], dtype=ppi.PintType())
was hitting registry issues as PintType() uses defaultregistry not my ureg. I'm not sure whether this is a big issue I'd imagine normal uses is to initialise from PintArray

Should try and get some series accessors that generate PintArrays so can be set as columns, eg:
df['torque_nm']=df['torque_in-lbf'].pint.to("nm")

**Comment by znicholls** [comment]
> Some documentation here.

Ok great will add that in and have a look.

> Those unitstrippedwarnings are really offputting too, should probably look into them

Yes that would be wise I think

**Comment by znicholls** [comment]
> Some documentation here.

Ok this is awesome. It would be great to add it into the docs. I don't know how to do that with all this `rst` stuff so would suggest initially just making a new directory called `notebooks` and sticking it in there. When we make the pull request we can ask how to add stuff to the docs properly.

While we're at it, it would be great to add tests for the `quantify` and `dequantify` methods

**Comment by znicholls** [comment]
> Are there any other features you were looking for @znicholls?

Nope everything in there looks great. To be honest a lot of the stuff is over my head so once we have docs written and tests passing I'll be happy. Examining actual implementation will be a job for when I make any future contributions, at the moment you seem to have taken care of it :)

**Comment by andrewgsavage** [comment]
> Ok this is awesome. It would be great to add it into the docs. I don't know how to do that with all this rst stuff so would suggest initially just making a new directory called notebooks and sticking it in there. When we make the pull request we can ask how to add stuff to the docs properly.

Yea me neither, will do that and below.
`

> While we're at it, it would be great to add tests for the quantify and dequantify methods


`

**Pull request merged**
